Deprecate lambdasoc and update gateware to Amaranth 0.5
greatscottgadgets/luna-soc pull request #33
Opened 2024-10-15 12:04 UTC by antoinevg

[ ] Bring generate code up to feature parity with luna-soc 0.2
[ ] Update top_level_cli
[ ] Update examples
[ ] General cleanup
[ ] Upstream changes and/or clarity re: supporting docstrings for register documentation

2025-02-06 19:09 UTC, vk2seb commented
Hey @antoinevg - this is awesome!

I expect to try to integrate this and will probably come back with some more comments/PRs after having tried it for a while. In any case, some early drive-by comments --

- The `lunasoc-hal` seems to be living in a different repository (at the moment a local path but I guess this will be fixed before merge), although it is applicable to many of the peripherals in this repository - would it make sense to migrate it here (or even a repository by itself)?
- Many of the providers in `provider/cynthion.py` don't seem to be cynthion-specific. In fact I think I would use the UART/QSPI/ULPI providers essentially unmodified, despite being on a completely different hardware platform. Perhaps some of these can remain living in a shared place here?
- I see the memory regions propagated to the Rust linker script are hard-coded, this stops me from being able to re-use this without modification as I have a psram region, but I see you're already planning to introspect :+1: 
- Would you guys be interested in adding at least one end-to-end simulation test of `luna-soc` (future work of course), I have found it quite useful to be able to simulate the whole SoC with Verilator, but it seems a lot of work has gone into CXXRTL recently, so maybe that would be the preferred approach. I'd be happy to help out with this. USB is probably too difficult at first (or maybe not? we could simulate USB gateware against another LUNA instance...), the other cores should be relatively easy to simulate end-to-end.

2025-02-07 14:55 UTC, antoinevg commented
> * The `lunasoc-hal` seems to be living in a different repository (at the moment a local path but I guess this will be fixed before merge), although it is applicable to many of the peripherals in this repository - would it make sense to migrate it here (or even a repository by itself)?

Yes, it currently lives in the https://github.com/greatscottgadgets/cynthion/ repository. I would definitely like to move it out of there eventually and into this repository, if only because the USB HAL code, in particular, is so tightly coupled to the gateware.

> * Many of the providers in `provider/cynthion.py` don't seem to be cynthion-specific. In fact I think I would use the UART/QSPI/ULPI providers essentially unmodified, despite being on a completely different hardware platform. Perhaps some of these can remain living in a shared place here?

That's a great idea, in fact that solves my problem because I'm not using any of the Cynthion-specific bits in the examples. Thank you @vk2seb!

> * I see the memory regions propagated to the Rust linker script are hard-coded, this stops me from being able to re-use this without modification as I have a psram region, but I see you're already planning to introspect 👍

Getting there, would love to hear about any specific requirements you may have e.g. being able to specify offsets for flash regions etc. :-)

> * Would you guys be interested in adding at least one end-to-end simulation test of `luna-soc` (future work of course), I have found it quite useful to be able to simulate the whole SoC with Verilator, but it seems a lot of work has gone into CXXRTL recently, so maybe that would be the preferred approach. I'd be happy to help out with this. USB is probably too difficult at first (or maybe not? we could simulate USB gateware against another LUNA instance...), the other cores should be relatively easy to simulate end-to-end.

_Hell_ yeah, any contributions in this area would be received with wide open arms!

2025-02-12 14:13 UTC, vk2seb commented
> Yes, it currently lives in the https://github.com/greatscottgadgets/cynthion/ repository. I would definitely like to move it out of there eventually and into this repository, if only because the USB HAL code, in particular, is so tightly coupled to the gateware.

Yes for the USB HAL definitely, but the timer and serial implementations are also tightly coupled to the gateware. It would also be a nicer place for me to be able to upstream e.g. my i2c peripheral and rust HAL: https://github.com/apfaudio/tiliqua/blob/main/gateware/src/tiliqua/i2c.py

> That's a great idea, in fact that solves my problem because I'm not using any of the Cynthion-specific bits in the examples. Thank you @vk2seb!

:partying_face: 

> Getting there, would love to hear about any specific requirements you may have e.g. being able to specify offsets for flash regions etc. :-)

Nothing too complicated, here are the parts that I needed to modify depending on SPIFLASH/PSRAM loading settings: https://github.com/apfaudio/tiliqua/blob/90754c1e7cb9c14356ad9ab3fcd923a9f6a6ea4c/gateware/src/tiliqua/tiliqua_soc.py#L460-L479

> Hell yeah, any contributions in this area would be received with wide open arms!

Awesome! will look into whether I can upstream some of my simulation work after this is merged :)

2025-02-12 14:33 UTC, antoinevg commented
> Yes for the USB HAL definitely, but the timer and serial implementations are also tightly coupled to the gateware. It would also be a nicer place for me to be able to upstream e.g. my i2c peripheral and rust HAL: https://github.com/apfaudio/tiliqua/blob/main/gateware/src/tiliqua/i2c.py

💯 they are more than welcome to hang out here until such time as/if things get more organized upstream!

> Nothing too complicated, here are the parts that I needed to modify depending on SPIFLASH/PSRAM loading settings: https://github.com/apfaudio/tiliqua/blob/90754c1e7cb9c14356ad9ab3fcd923a9f6a6ea4c/gateware/src/tiliqua/tiliqua_soc.py#L460-L479

Tx!

2025-03-04 16:27 UTC, miek commented on pyproject.toml
> +    "luna-usb~=0.3",
I'm not sure this extra version bump is necessary? The dep was already bumped to 0.2 in an earlier commit.

2025-03-04 16:51 UTC, antoinevg commented on pyproject.toml
> +    "luna-usb~=0.3",
Whoopsie, butter fingers! Fixed in: [bd12c3e](https://github.com/antoinevg/luna-soc/commit/bd12c3ea7b24793b2e7bc8e1916694d6679e1039)

2025-03-14 09:18 UTC, mndza commented on luna_soc/gateware/core/memory.py
Is there a reason for keeping this? We already have `WishboneRAM` from `amaranth_soc`.

2025-03-14 09:33 UTC, mndza commented on luna_soc/gateware/core/sram.py
Should we also keep this also? Looks like `amaranth_soc`'s `WishboneSRAM` provides the same.

2025-03-17 08:17 UTC, mndza commented on luna_soc/gateware/core/timer.py
> +        regs = csr.Builder(addr_width=4, data_width=8)
Why is `data_width` set to 8 here instead of 32 like in lambdasoc?

2025-03-17 08:19 UTC, mndza commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
Zero is not being set when the periodic mode is disabled.

2025-03-17 09:42 UTC, mndza commented on luna_soc/gateware/core/usb2/ep_control.py
> +        address : csr.Field(csr.action.W,       unsigned(8))
What's the reason for separating the address RW register in two?

2025-03-17 13:20 UTC, antoinevg commented on luna_soc/gateware/core/memory.py
Yeah, I've also been thinking that. At one point it was being used by examples but I've switched them all over to `blockram`. Removed in: 4215056d037095f2b3b34c178512fcac1bddafa7

2025-03-17 13:44 UTC, antoinevg commented on luna_soc/gateware/core/timer.py
> +        regs = csr.Builder(addr_width=4, data_width=8)
I think timer is the only csr peripheral that has a > 8 bit register field and I'm trying to keep resource usage down on both gateware and firmware side.

What do you think? Is it worth having a 32-bit data-bus for the csr peripherals if it hardly ever gets used?

2025-03-17 13:51 UTC, antoinevg commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
You're right, it only does interrupts for periodic timers. Didn't catch that because the code examples that use the non-periodic mode are all polling the register instead. 🥲

Fixed in: 4610bfd

2025-03-17 13:57 UTC, mndza commented on luna_soc/gateware/core/timer.py
> +        regs = csr.Builder(addr_width=4, data_width=8)
Fair. Did you check that the resource usage is in fact lower? IIRC for CSR, if a field width is wider than the datapath width, shadow registers are instantiated to provide atomic reads/writes.

2025-03-17 14:02 UTC, antoinevg commented on luna_soc/gateware/core/usb2/ep_control.py
> +        address : csr.Field(csr.action.W,       unsigned(8))
So this is pretty cool! With the new register field access model we also got an ownership model that makes explicit the relationship between peripheral and the bus-initiator. So, in this case, you can no longer have `RW` field _and_ have a strobe field under control of the peripheral as this can introduce write conflicts.

Full details: https://amaranth-lang.org/rfcs/0016-soc-csr-regs.html#field-access-and-ownership

2025-03-17 14:06 UTC, antoinevg commented on luna_soc/gateware/core/timer.py
> +        regs = csr.Builder(addr_width=4, data_width=8)
I did check, there's about a 10% gain on the gateware side and we got back about 2 kilobytes on the firmware!

That said, what should _also_ have done is allow `data_width` specification for the new peripheral constructors in the same way that amaranth-soc's gpio peripheral does it:

https://github.com/amaranth-lang/amaranth-soc/blob/5c43cf58f15d9cd9c69ff83c97997708d386b2dc/amaranth_soc/gpio.py#L260

2025-03-17 15:16 UTC, mndza commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
Why is the `reload != 0` check needed when the periodic mode is disabled?

2025-03-17 15:31 UTC, antoinevg commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
So we don't DOS the CPU if someone enables interrupts before configuring the reload register. 🌊

2025-03-17 15:34 UTC, mndza commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
It will DOS the CPU anyway when `reload != 0`: `counter` will still be 0.

2025-03-17 16:54 UTC, mndza commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
I'm not convinced about this, because you are only delaying the problem.
If you want to set it to the max value at underflow, you can do this instead:
```python
with m.If(self._enable.f.enable.data):
    m.d.comb += zero.eq(self._counter.f.value.r_data == 0)
    with m.If((self._counter.f.value.r_data == 0) & (self._mode.f.periodic.data == 1)):
        m.d.sync += self._counter.f.value.r_data.eq(self._reload.f.value.data)
    with m.Else():
        m.d.sync += self._counter.f.value.r_data.eq(self._counter.f.value.r_data - 1)
with m.Else():
    m.d.sync += self._counter.f.value.r_data.eq(self._reload.f.value.data)
```

2025-03-18 12:13 UTC, antoinevg commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
So I've ended up doing the RightThing™ instead and cleaned up the logic into a more readable FSM:

```python
        # peripheral logic
        zero = Signal()
        with m.FSM():
            with m.State("IDLE"):
                with m.If(self._enable.f.enable.data == 1):
                    m.d.sync += self._counter.f.value.r_data.eq(self._reload.f.value.data)
                    m.next = "COUNT"
            with m.State("COUNT"):
                with m.If(self._counter.f.value.r_data == 0):
                    m.d.comb += zero.eq(1)
                    m.next = "DONE"
                with m.Else():
                    m.d.sync += self._counter.f.value.r_data.eq(self._counter.f.value.r_data - 1)
            with m.State("DONE"):
                with m.If(self._mode.f.periodic.data == 1):
                    m.next = "IDLE"
                with m.Elif(self._enable.f.enable.data == 0):
                    m.next = "IDLE"
```

For reference, here's an example of what the driver code looks like on the firmware side:

```rust
                fn delay_us(&mut self, us: u32) -> Result<(), Self::Error> {
                    let ticks: u32 = self.clk / 1_000_000 * us;

                    // reset timer
                    self.registers.enable().write(|w| w.enable().bit(false));

                    // start timer
                    self.set_mode($crate::timer::Mode::OneShot);
                    self.registers.reload().write(|w| unsafe { w.value().bits(ticks) });
                    self.registers.enable().write(|w| w.enable().bit(true));

                    // wait for timer to hit zero
                    while self.registers.counter().read().value().bits() != 0 {}

                    Ok(())
                }
```

Commit: d6ae32abbdf80e915d02512eddccc05e6e9da746

2025-03-18 12:35 UTC, zyp commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
`csr.Field` passes `*args` and `**kwargs` on to the selected action class, and the constructor of [`action.RW`](https://github.com/amaranth-lang/amaranth-soc/blob/5c43cf58f15d9cd9c69ff83c97997708d386b2dc/amaranth_soc/csr/action.py#L94) does take an `init` argument, so unless I'm overlooking something, it *is* supported.

2025-03-18 12:45 UTC, mndza commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
> So I've ended up doing the RightThing™ instead and cleaned up the logic into a more readable FSM:

I see a couple problems with the FSM approach: it adds idle cycles between runs in periodic mode and the timer can only be disabled when it hits zero.
You could set a flag instead that avoids repeatedly asserting `zero` in one-shot mode:

```python
zero = Signal()
triggered = Signal()
m.d.sync += triggered.eq(zero & ~self._mode.f.periodic.data)

with m.If(self._enable.f.enable.data):
    with m.If(self._counter.f.value.r_data == 0):
        m.d.comb += zero.eq(~triggered)
        with m.If(self._mode.f.periodic.data):
            m.d.sync += self._counter.f.value.r_data.eq(self._reload.f.value.data)
    with m.Else():
        m.d.sync += self._counter.f.value.r_data.eq(self._counter.f.value.r_data - 1)
with m.Else():
    m.d.sync += self._counter.f.value.r_data.eq(self._reload.f.value.data)
```

2025-03-18 12:56 UTC, mndza commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
> So I've ended up doing the RightThing™ instead and cleaned up the logic into a more readable FSM:

I see a couple problems with the FSM approach: it adds idle cycles between runs in periodic mode and the timer can only be disabled when it hits zero.
You could set a flag instead that avoids repeatedly asserting `zero` in one-shot mode:

```python
zero = Signal()
triggered = Signal()

with m.If(self._enable.f.enable.data):
    with m.If(self._counter.f.value.r_data == 0):
        m.d.comb += zero.eq(~triggered)
        with m.If(self._mode.f.periodic.data):
            m.d.sync += self._counter.f.value.r_data.eq(self._reload.f.value.data)
        with m.Else():
            m.d.sync += triggered.eq(1)
    with m.Else():
        m.d.sync += self._counter.f.value.r_data.eq(self._counter.f.value.r_data - 1)
with m.Else():
    m.d.sync += self._counter.f.value.r_data.eq(self._reload.f.value.data)
    m.d.sync += triggered.eq(0)
```

EDIT: the previous comment had an obvious bug :sweat:

2025-03-18 13:07 UTC, zyp commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
I don't think `action.R` is meant to be stateful. If you make a separate counter state signal and do a combinational assignment to `r_data`, you can set `init` on the state signal.

2025-03-18 13:23 UTC, antoinevg commented on luna_soc/gateware/core/timer.py
> +                m.d.comb += zero.eq(1)
Cool updated conditional passes all tests -- nice one @mndza !

Fixed in: a9569ea3634393159b132c6e378dd7a14a5f32c3

2025-03-23 17:07 UTC, zyp commented on luna_soc/gateware/core/usb2/ulpi.py
> +            "data" : In(
This is incorrect; when you have an `In` signature member, the direction of its child members are flipped, so `data.i` ends up being an output, and vice versa.

2025-03-23 17:08 UTC, zyp commented on luna_soc/gateware/core/usb2/ulpi.py
> +            "nxt" : In  (wiring.Signature({ "i" : In  (unsigned(1)) })),
Same issue here; both `clk.o` and `nxt.i` ends up being outputs.

2025-03-26 14:34 UTC, mndza requested changes
Please address the signature issues that @zyp pointed out.

2025-03-27 13:39 UTC, antoinevg commented on luna_soc/gateware/core/usb2/ulpi.py
> +            "data" : In(
Argh, that hurts my head… but thank you!

2025-03-27 13:42 UTC, antoinevg commented on luna_soc/gateware/core/usb2/ulpi.py
> +            "data" : In(
Fixed in: 84c942190ace95a8e2e4b8482cd2983fec014232

2025-03-27 13:42 UTC, antoinevg commented on luna_soc/gateware/core/usb2/ulpi.py
> +            "nxt" : In  (wiring.Signature({ "i" : In  (unsigned(1)) })),
Fixed in: 84c942190ace95a8e2e4b8482cd2983fec014232

2025-04-01 15:27 UTC, mndza approved these changes

2025-04-03 13:11 UTC, merged